version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PG_DATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./tmp:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 1s

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '8000:80'
    depends_on:
      db:
        condition: service_healthy
